# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\python_in_qgis_arcgis\PIQAA\exercise_8\muenster_city_district_tool\exportDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 457)
        self.exportBox = QtWidgets.QGroupBox(Dialog)
        self.exportBox.setGeometry(QtCore.QRect(20, 20, 521, 421))
        self.exportBox.setObjectName("exportBox")
        self.btnPDF = QtWidgets.QPushButton(self.exportBox)
        self.btnPDF.setGeometry(QtCore.QRect(10, 30, 271, 61))
        self.btnPDF.setObjectName("btnPDF")
        self.label = QtWidgets.QLabel(self.exportBox)
        self.label.setGeometry(QtCore.QRect(20, 100, 491, 51))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.btnCSV = QtWidgets.QPushButton(self.exportBox)
        self.btnCSV.setGeometry(QtCore.QRect(12, 191, 271, 61))
        self.btnCSV.setObjectName("btnCSV")
        self.label_2 = QtWidgets.QLabel(self.exportBox)
        self.label_2.setGeometry(QtCore.QRect(20, 260, 481, 31))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.btnOK = QtWidgets.QPushButton(self.exportBox)
        self.btnOK.setGeometry(QtCore.QRect(120, 350, 261, 41))
        self.btnOK.setObjectName("btnOK")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exportBox.setTitle(_translate("Dialog", "Export in Datei"))
        self.btnPDF.setText(_translate("Dialog", "Export als *.pdf"))
        self.label.setText(_translate("Dialog", "Die Werte des selektieren Features werden in einen *.pdf-Steckbrief geschrieben. Bitte geben Sie hierzu noch einen Ausgabepfad an. Bitte beachten Sie,  dass nur ein Feature ausgewählt ist."))
        self.btnCSV.setText(_translate("Dialog", "Export als *.csv"))
        self.label_2.setText(_translate("Dialog", "Die Werte der selektierten Feature werden in eine *.csv exportiert. Bitte geben Sie hirzu noch einen Ausgabepfad an."))
        self.btnOK.setText(_translate("Dialog", "OK"))
