# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\python_in_qgis_arcgis\PIQAA\exercise_8\muenster_city_district_tool\muenster_city_district_tool_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MuensterCityDistrictToolDialogBase(object):
    def setupUi(self, MuensterCityDistrictToolDialogBase):
        MuensterCityDistrictToolDialogBase.setObjectName("MuensterCityDistrictToolDialogBase")
        MuensterCityDistrictToolDialogBase.resize(455, 380)
        self.button_box = QtWidgets.QDialogButtonBox(MuensterCityDistrictToolDialogBase)
        self.button_box.setGeometry(QtCore.QRect(50, 300, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(MuensterCityDistrictToolDialogBase)
        self.label.setGeometry(QtCore.QRect(30, 20, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MuensterCityDistrictToolDialogBase)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 301, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MuensterCityDistrictToolDialogBase)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 211, 16))
        self.label_3.setObjectName("label_3")
        self.btnGetData = QtWidgets.QPushButton(MuensterCityDistrictToolDialogBase)
        self.btnGetData.setGeometry(QtCore.QRect(100, 150, 281, 51))
        self.btnGetData.setObjectName("btnGetData")
        self.btnExportData = QtWidgets.QPushButton(MuensterCityDistrictToolDialogBase)
        self.btnExportData.setGeometry(QtCore.QRect(100, 210, 281, 51))
        self.btnExportData.setObjectName("btnExportData")

        self.retranslateUi(MuensterCityDistrictToolDialogBase)
        self.button_box.accepted.connect(MuensterCityDistrictToolDialogBase.accept)
        self.button_box.rejected.connect(MuensterCityDistrictToolDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MuensterCityDistrictToolDialogBase)

    def retranslateUi(self, MuensterCityDistrictToolDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MuensterCityDistrictToolDialogBase.setWindowTitle(_translate("MuensterCityDistrictToolDialogBase", "Muenster City District Tool"))
        self.label.setText(_translate("MuensterCityDistrictToolDialogBase", "Muenster City District Tool"))
        self.label_2.setText(_translate("MuensterCityDistrictToolDialogBase", "Use the tools to query values directly or to export "))
        self.label_3.setText(_translate("MuensterCityDistrictToolDialogBase", "the values of the selcted feautres"))
        self.btnGetData.setText(_translate("MuensterCityDistrictToolDialogBase", "Get data from the selcted features"))
        self.btnExportData.setText(_translate("MuensterCityDistrictToolDialogBase", "Export data from the selected features"))
